services:
  rsyntaxtree_service:
    image: yohasebe/syntree
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_TAG: "monadic-chat"
    container_name: monadic-chat-syntree-container
    depends_on:
      - ruby_service
    networks:
      - monadic-chat-network
    volumes:
      - data:/monadic/data
      - ~/monadic/data:/monadic/data
    stdin_open: true
    tty: true
